"""empty message

Revision ID: 08ef3e81d071
Revises: 23f3a15a2329
Create Date: 2022-07-29 13:00:17.500770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ef3e81d071'
down_revision = '23f3a15a2329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rec',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['rec.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('rec', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_rec_timestamp'), 'rec', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rec_timestamp'), table_name='rec')
    op.drop_column('rec', 'timestamp')
    op.drop_table('user_rec')
    # ### end Alembic commands ###
