"""empty message

Revision ID: 10f6326488df
Revises: 50b1e1ad942c
Create Date: 2022-08-01 16:03:24.295742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f6326488df'
down_revision = '50b1e1ad942c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rec', 'image_url')
    # ### end Alembic commands ###
