"""empty message

Revision ID: 23f3a15a2329
Revises: d4743cf091ac
Create Date: 2022-07-27 18:17:42.827434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f3a15a2329'
down_revision = 'd4743cf091ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('restaurant_name', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('yelp_id', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('yelp_url', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('price', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('category1', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('category2', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('category3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rec', 'category3')
    op.drop_column('rec', 'category2')
    op.drop_column('rec', 'category1')
    op.drop_column('rec', 'price')
    op.drop_column('rec', 'yelp_url')
    op.drop_column('rec', 'yelp_id')
    op.drop_column('rec', 'restaurant_name')
    # ### end Alembic commands ###
