"""empty message

Revision ID: 576b7149befe
Revises: 2241960f658c
Create Date: 2022-07-27 15:26:47.053972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576b7149befe'
down_revision = '2241960f658c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_user',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'friend_id')
    )
    op.drop_constraint('user_friend_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'friend_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_friend_id_fkey', 'user', 'user', ['friend_id'], ['id'])
    op.drop_table('user_to_user')
    # ### end Alembic commands ###
