"""empty message

Revision ID: 5f4049621507
Revises: 08ef3e81d071
Create Date: 2022-07-29 13:35:30.292831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4049621507'
down_revision = '08ef3e81d071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rec', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rec', type_='foreignkey')
    op.drop_column('rec', 'user_id')
    # ### end Alembic commands ###
