"""empty message

Revision ID: 90bb16113c99
Revises: b98546d3220f
Create Date: 2022-08-03 17:31:15.817911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bb16113c99'
down_revision = 'b98546d3220f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('rec', sa.Column('location_state', sa.String(), nullable=True))
    op.drop_column('rec', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rec', 'location_state')
    op.drop_column('rec', 'location_city')
    # ### end Alembic commands ###
