"""empty message

Revision ID: b98546d3220f
Revises: 10f6326488df
Create Date: 2022-08-03 17:20:59.427247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98546d3220f'
down_revision = '10f6326488df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rec', 'location')
    # ### end Alembic commands ###
